version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'my_database'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: '12345'
    ports:
      - "6666:5432"
    #volumes:
    #  - db-data:/var/lib/postgresql/data

#volumes:
#  db-data:
